---
- name: Download golang tools
  get_url:
    url: https://dl.google.com/go/go{{ golang_version }}.{{ os_version }}-{{ arch_version }}.tar.gz
    dest: ~/go{{ golang_version }}.{{ os_version }}-{{ arch_version }}.tar.gz 

- name: Unarchive golang tools
  unarchive:
    src: ~/go{{ golang_version }}.{{ os_version }}-{{ arch_version }}.tar.gz
    dest: ~/
    remote_src: yes

- name: Rename filename from ~/go -> ~/.go
  block:
    - name: Check go dir
      stat:
        path: ~/go
      register: go_path

    - name: rename go path
      command: mv ~/go ~/.go
      when: go_path.stat.exists
    
