---
- name: Restart mysql for Debian
  shell: /etc/init.d/mysql restart

- name: Restart mysql for RedHat
  systemd:
    name: mysql
    state: restarted
    daemon_reload: yes 

- name: Create mysql database
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items:
    - test_db

- name: Create mysql user
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.db }}.*:ALL,GRANT"
    state: present
  with_items:
    - { name: "test_user", host: "192.168.33.10", password: "test_password", db: "test_db" }